name: Build and Push Docker Image to Google Artifact Registry

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Extract Version Tag
        id: tag
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Auth
        id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_RESTAKE_SA_KEY }}'

      - name: Configure Docker for Google Artifact Registry
        run: gcloud auth configure-docker ${{ secrets.GCP_ARTIFACT_REGISTRY }}

      - name: Build and Push Docker Image to Google Artifact Registry
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.GCP_ARTIFACT_REGISTRY }}/${{ secrets.GCP_RESTAKE_IMAGE_PATH }}/restake:${{ env.TAG_NAME }}
